# Generated by Django 3.2.5 on 2021-07-06 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, null=True, verbose_name='Student ID')),
                ('student_name', models.CharField(max_length=120, verbose_name='Student Name')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, null=True, verbose_name='Teacher ID')),
                ('teacher_name', models.CharField(max_length=120, verbose_name='Teacher Name')),
                ('teacher_email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20, null=True, verbose_name='Course ID')),
                ('course_name', models.CharField(max_length=120, verbose_name='Course Name')),
                ('student', models.ManyToManyField(blank=True, to='course.Student')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.teacher')),
            ],
        ),
    ]
